# Generated by Django 5.0.4 on 2024-04-15 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Author's Name")),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Book Title')),
                ('page_count', models.IntegerField(verbose_name='Number of Pages')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('cover_type', models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, verbose_name='Cover type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Book Cover')),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='market.author', verbose_name='Author')),
                ('category', models.ManyToManyField(to='market.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Book',
                'ordering': ['-price'],
            },
        ),
    ]
