# Generated by Django 5.0.4 on 2024-04-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Young Adult', 'Young Adult'), ('Non-Fiction', 'Non-Fiction'), ('Historical Fiction', 'Historical Fiction'), ('Biography', 'Biography')], max_length=100, verbose_name='Category Name'),
        ),
    ]
