# Generated by Django 5.0.4 on 2024-04-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name_af',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ar_dz',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ast',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_az',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_be',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_bg',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_bn',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_br',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_bs',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ca',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ckb',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_cs',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_cy',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_da',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_dsb',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_el',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_en_au',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_en_gb',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_eo',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_es_ar',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_es_co',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_es_mx',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_es_ni',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_es_ve',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_et',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_eu',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_fy',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ga',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_gd',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_gl',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_he',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_hi',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_hr',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_hsb',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_hu',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_hy',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ia',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ig',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ind',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_io',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_is',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ja',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ka',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_kab',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_km',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_kn',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ko',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_lb',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_lt',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_lv',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_mk',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ml',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_mn',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_mr',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ms',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_my',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_nb',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ne',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_nn',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_os',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_pa',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ro',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_sk',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_sl',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_sq',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_sr',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_sr_latn',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_sv',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_sw',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ta',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_te',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_tg',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_th',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_tk',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_tt',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_udm',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ug',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ur',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_vi',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='author',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_af',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ar',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ar_dz',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ast',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_az',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_be',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_bg',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_bn',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_br',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_bs',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ca',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ckb',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_cs',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_cy',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_da',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_de',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_dsb',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_el',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_en',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_en_au',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_en_gb',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_eo',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_es',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_es_ar',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_es_co',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_es_mx',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_es_ni',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_es_ve',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_et',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_eu',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_fa',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_fi',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_fr',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_fy',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ga',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_gd',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_gl',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_he',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_hi',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_hr',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_hsb',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_hu',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_hy',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ia',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ig',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ind',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_io',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_is',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_it',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ja',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ka',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_kab',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_kk',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_km',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_kn',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ko',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ky',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_lb',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_lt',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_lv',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_mk',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ml',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_mn',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_mr',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ms',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_my',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_nb',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ne',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_nl',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_nn',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_os',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_pa',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_pl',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_pt',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_pt_br',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ro',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ru',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_sk',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_sl',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_sq',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_sr',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_sr_latn',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_sv',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_sw',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ta',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_te',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_tg',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_th',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_tk',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_tr',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_tt',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_udm',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ug',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_uk',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_ur',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_uz',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_vi',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_zh_hans',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type_zh_hant',
            field=models.CharField(choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('SP', 'Special')], default='HC', max_length=2, null=True, verbose_name='Cover type'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_af',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ar_dz',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ast',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_be',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_bg',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_bn',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_bs',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ckb',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_cs',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_cy',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_da',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_dsb',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_el',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_en_au',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_en_gb',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_eo',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_es_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_es_co',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_es_mx',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_es_ni',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_es_ve',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_et',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_eu',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_fy',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ga',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_gd',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_gl',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_he',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_hi',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_hr',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_hsb',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_hu',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_hy',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ia',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ig',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ind',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_io',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_is',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ja',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ka',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_kab',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_km',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_kn',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ko',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_lb',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_lt',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_lv',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_mk',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ml',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_mn',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_mr',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ms',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_my',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_nb',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ne',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_nn',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_os',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_pa',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ro',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_sk',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_sl',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_sq',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_sr_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_sv',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_sw',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ta',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_te',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_tg',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_th',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_tk',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_tt',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_udm',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ug',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ur',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_vi',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_af',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar_dz',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ast',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_be',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_bg',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_bn',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_br',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_bs',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ca',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ckb',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_cs',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_cy',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_da',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_dsb',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_el',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_au',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_gb',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_eo',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_ar',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_co',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_mx',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_ni',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_ve',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_et',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_eu',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fy',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ga',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_gd',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_gl',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_he',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hi',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hsb',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hu',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hy',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ia',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ig',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ind',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_io',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_is',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_it',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ja',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ka',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kab',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_km',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kn',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ko',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lb',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lt',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lv',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mk',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ml',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mn',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ms',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_my',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nb',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ne',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nn',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_os',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pa',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ro',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sk',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sl',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sq',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sr_latn',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sv',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sw',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ta',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_te',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tg',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_th',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tk',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tt',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_udm',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ug',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ur',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_vi',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
    ]
