# Generated by Django 5.0.4 on 2024-04-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_author_name_af_remove_author_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name_ka',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_type_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_type_ka',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name_ka',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ka',
        ),
    ]
